export const FIND_LESSON_FOR_MODULE  = "FIND_LESSON_FOR_MODULE"
export const CREATE_LESSON  = "CREATE_LESSON"
export const DELETE_LESSON  = "DELETE_LESSON"
export const UPDATE_LESSON  = "UPDATE_LESSON"